sign up page draft
imiryna/WaterTracker pull request #11
Opened 2024-01-27 18:52 UTC by ndnastia

2024-01-27 20:50 UTC, imiryna commented on src/Redux/auth/authSlice.js
> +import { loginThunk, registerThunk } from './authThank';
from './authThank' => authThUnk'

2024-01-27 20:58 UTC, zoobeen1 requested changes, later dismissed

2024-01-27 20:58 UTC, zoobeen1 commented on src/Redux/auth/authThank.js
Меня смущает название - во первых не Thank a Thunk - во вторых - лучше использовать что-то типа - authOperations - IMHO

2024-01-27 20:58 UTC, zoobeen1 commented on src/Redux/auth/authSlice.js
> +import { loginThunk, registerThunk } from './authThank';
Поменять название санки

2024-01-28 18:53 UTC, imiryna approved these changes

2024-01-28 18:56 UTC, merged