Today normal/modal
imiryna/WaterTracker pull request #22
Opened 2024-01-29 20:37 UTC by JemJoestar

додав модалку з формою для зміни денної норми

2024-01-29 22:59 UTC, NeoZLoy requested changes

2024-01-29 22:59 UTC, NeoZLoy commented on src/components/DailyNorma/DailyNorma.jsx
> +  const GENDER = {
Гендер нужно брать из модели currentUser. Эта инфа хранится в настройках юзера. Нужно переписать эту логику под получение денных с бека, по сути, прикрутить useSelector() который появится когда-то потом)

2024-01-29 22:59 UTC, NeoZLoy commented on src/components/DailyNorma/DailyNorma.jsx
> +import { StyledDalyNorma } from './dailyNorma.styled';
DailyNorma.styled (с большой буквы)

2024-01-29 22:59 UTC, NeoZLoy commented on src/components/DailyNorma/DailyNorma.styled.jsx
> +  .title {
добавь везде font-family, font-weight, чтобы не забыть

2024-01-29 22:59 UTC, NeoZLoy commented on src/components/DailyNorma/EditNormaModal.styled.jsx
> +  .description {
в этом фалйе тоже font-family, font-weight, просмотри везде

2024-01-29 23:04 UTC, imiryna commented on src/components/DailyNorma/DailyNorma.jsx
> +  const [gender, setGender] = useState(GENDER.male);
Це все дані currentUser. Треба через Redux.

2024-01-31 10:09 UTC, NeoZLoy approved these changes
must work c:

2024-01-31 18:42 UTC, imiryna approved these changes

2024-01-31 22:28 UTC, imiryna approved these changes

2024-01-31 22:43 UTC, imiryna approved these changes
LG

2024-02-02 10:02 UTC, closed without merging

2024-02-02 10:02 UTC, imiryna commented
duplicated, already merged in another PR